# Generated by Django 5.0.6 on 2024-05-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0003_tour_trip_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='Trip_Detail',
            field=models.TextField(verbose_name='Tour descirption'),
        ),
    ]
