# Generated by Django 5.0.6 on 2024-05-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customer_birthday_alter_customer_e_posta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Customer Name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Customer Lastname')),
                ('Tel_No', models.CharField(max_length=10, null=True, verbose_name='Phone Number')),
                ('Emergency_Number', models.CharField(max_length=10, null=True)),
                ('Birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('Gender', models.CharField(max_length=10, null=True, verbose_name='Gender')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_permissions',
        ),
    ]
